---
title: "GPA with surface semilandmarks"
---

```{r, echo=F}
knitr::read_chunk("scripts/GPASurface.R")
knitr::opts_chunk$set(dev.args=list(bg = 'transparent'), fig.align = 'center', class.source = ".custom-inline", class.output = ".custom-inline")
options(rgl.printRglwidget = TRUE)
```

```{r, prelims, include=FALSE}

```

## **Performing a GPA with sliding semilandmarks on surfaces**

As with curve semilandmarks, the `gpagen` function requires that the user identify which landmarks are to be treated as surface semilandmarks: 

<div class = "code">
```{r, surfdata, eval=TRUE}

```
</div>
<br></br>

This takes the form of a simple vector (above) that lists the surface semilandmarks. This matrix is specified under the `surfaces` argument as shown here:

<div class = "code">
```{r, eval=FALSE}
GPA <- gpagen(scallops$coorddata,curves = scallops$curvslide, surfaces = scallops$surfslide, print.progress = FALSE)

plotAllSpecimens(GPA$coords)
rglwidget()
```
</div>
<br></br>

```{r, GPA3, fig.align='center', echo=FALSE}

```