---
  title: "Course content"
---
The course is organized in both theoretical and practical sessions. Lectures provide a solid theoretical understanding of the mathematical underpinnings of the procedures for proper analysis of shape data from landmark coordinates. Laboratory sessions put these concepts into practice, and include worked examples, giving participants the opportunity to gain hands-on experience in the treatment of shape data using the R package geomorph. All stages of a morphometric analysis will be covered: data collection, the statistical treatment of shape variation with respect to biological hypotheses, and the visualization of patterns of shape variation and of the shapes themselves for interpretation of statistical findings, using the R language for statistical programming. While practice datasets will be available, it is strongly recommended that participants come with their own datasets.

Note: Because this is a geometric morphometrics workshop in R, it is assumed that participants have some working knowledge in R, as the practical sessions will focus on GM-based analyses (not basic R use). It is therefore strongly recommended that participants refresh their R skills prior to attending the workshop.


* **Monday**
    + Morphometrics: History, Introduction and Data Types
    + Linear Algebra and Linear Models 
    + Introduction to gmShiny
    + Software demonstration (SD) and lab practicum 
    
* **Tuesday**
    + Superimposition
    + Shape Spaces, Shape Variables, & PCA 
    + GPA with Semilandmarks
    + SD and lab
    
* **Wednesday**
    + Shape Statistics I
    + Allometry
    + Shape Statistics II
    + SD and lab    

* **Thursday**
    + Phylogenetic Shape Variation
    + Asymmetry
    + Disparity
    + Integration and Modularity 
    + SD and lab
    
* **Friday**
    + Missing Data
    + Future Directions and Prospectus
    + Student Presentations
    
    
