--- 
  title: "Geometric Morphometrics in R"
---

#### Geometric Morphometric Analysis in Ecology and Evolutionary Biology Using R

### 8 - 12 May 2023, Barcelona, Spain
<br>
The field of geometric morphometrics (GM) is concerned with the quantification and analysis of patterns of shape variation, and its covariation with other variables. The goal of this workshop is to provide participants with both working knowledge of the theory of geometric morphometrics, as well as practical training in the application of these methods. 

The course will take place in the [Faculty of Biology of the University of Barcelona](https://www.ub.edu/portal/web/biologia/) and is organized by the [Department of Evolutionary Biology, Ecology and Environmental Science](https://www.ub.edu/portal/web/dp-beeca/) and the [Institute of Research in Biodiversity](http://www.ub.edu/irbio/home). 

<br>

This is considered a post-graduate course, approved by the Faculty of Biology of the UB, and it corresponds to 3 ECTS units, for students interested in validating and transferring credits for it. It is, however, open as an international workshop to participants at any stage of their academic career.
For the information of the course in UB, see [here](https://www.ub.edu/web/ub/es/estudis/oferta_formativa/extensions/fitxa/G/202111708/index.html) 

<br>

The **cost** of the course will be of 350 euros per participant.

<br>

### Application procedure
To apply for participating in the course please feel in the application form [here](https://forms.gle/SppEEYe6cYXmdp9q7)

Up to 25 participants will be accepted on the basis of their academic career stage (priority given to PhD students and early-career researchers) and relevance of the course for their research.

<br>

### The **deadline for applications** is November 15, 2022. 
Admitted participants will be informed until December 15, 2022.

<br>

For more information or inquiries [send us an email](gmcourseub@gmail.com)
