---
  title: "Lab Tutorials and Data"
---

Note that the days correspond to days of lectures, which may differ from the days in the workshop (especially if the first day of the workshop is dedicated to digitizing practices).

### Tutorial on GPA and Visualization

- [R-Based Review of Day 1 Material: ](https://geomorphR.github.io/GMcourse/Labs/01-Day1Material.html)
- [Day 1 R-script](https://geomorphR.github.io/GMcourse/Labs/01-Day01-RCode.R)

### Tutorial on GPA with semilandmarks, PLS, and Linear Regression

- [R-Based Review of Day 2 Material:](https://geomorphR.github.io/GMcourse/Labs/02-Day2Material.html)
- [Day 2 R-script](https://geomorphR.github.io/GMcourse/Labs/02-Day02-RCode.R)

### Tutorial on GLM analyses, phylogenetic comparative methods, symmetry, and measurement error

- [R-Based Review of Day 3 Material:](https://geomorphR.github.io/GMcourse/Labs/03-Day3Material.html)
- [Day 3 R-script:](https://geomorphR.github.io/GMcourse/Labs/03-Day03-RCode.R)

### Tutorial on trajectory analysis, morphological disparity, modularity, and integration

- [R-Based Review of Day 4 Material:](https://geomorphR.github.io/GMcourse/Labs/04-Day4Material.html)
- [Day 4 R-script](https://geomorphR.github.io/GMcourse/Labs/04-Day04-RCode.R)

### Additional Material
- [Digitizing in Stereomorph Tutorial](https://geomorphR.github.io/GMcourse/Labs/00-Stereomorph-Tutorial.html)
- [Digitizing in Stereomorph R-Script](https://geomorphR.github.io/GMcourse/Labs/00-Stereomorph-RCode.R)

### Example data for Workshop (can be cloned, pulled, or files downloaded)
[Link to Data Repository](https://github.com/geomorphR/geomorphR.github.io/tree/main/GMcourse/Labs/Data)

[Tool for downloading all data or just subfolders](https://download-directory.github.io/)  (Requires entering url.)
