---
  title: "Reference List"
---

**Software Packages**

Baken, E.K., M.L. Collyer, A. Kaliontzopoulou, and D.C. Adams. 2021. geomorph v4.0 and gmShiny: enhanced analytics and a new graphical interface for a comprehensive morphometric experience. *Methods in Ecology and Evolution*. 12:2355–2363.

Collyer, M.L, and D.C. Adams. 2018. RRPP: An R package for fitting linear models to high-dimensional data using residual randomization. *Methods in Ecology and Evolution*. 9:1772-1779.

**General Overview of Geometric Morphometrics**

Adams, D.C., F. J. Rohlf, and D.E. Slice. 2013. A field comes of age: Geometric morphometrics in the 21^st^ century. *Hystrix.* 24:7-14.

**General Analytical Theory of Methods**

Adams, D.C. and M.L. Collyer. 2022.  Consilience of methods for phylogenetic analysis of variance. *Evolution*. 76:1406–1419.

Conaway, M.A., and D.C. Adams. 2022. An effect size for comparing the strength of morphological integration across studies. *Evolution*. 76: 2244-2259.

Collyer, M.L., and D.C. Adams. 2021. Phylogenetically aligned component analysis. *Methods in Ecology and Evolution*. 12:359-372.

Collyer, M.L., M.A. Davis, and D.C. Adams. 2020. Making heads or tails of combined landmark configurations in geometric morphometric data. *Evolutionary Biology*. 47:193-205.

Adams, D.C., and M.L. Collyer. 2019. Comparing the strength of modular signal, and evaluating alternative modular hypotheses, using covariance ratio effect sizes with morphometric data. *Evolution*. 73:2352-2367.

Adams, D.C., and M.L. Collyer. 2019. Phylogenetic comparative methods and the evolution of multivariate phenotypes. *Annual Review of Ecology, Evolution, and Systematics*. 50:405-425.

Adams, D.C. , and M.L. Collyer. 2018. Phylogenetic ANOVA: Group-clade aggregation, biological challenges, and a refined permutation procedure. *Evolution*. 72:1204-1215.

Adams, D.C., and M.L. Collyer. 2018. Multivariate phylogenetic comparative methods: Evaluations, comparisons, and recommendations. *Systematic Biology*. 67:14-31. 

Adams, D.C. and M.L. Collyer. 2016. On the comparison of the strength of morphological integration across morphometric datasets. *Evolution*. 70:2623-2631.

Adams, D.C.. 2016. Evaluating modularity in morphometric data: Challenges with the RV coefficient and a new test measure. *Methods in Ecology and Evolution.* 7:565-572. 

Davis, M.A., M.R. Douglas, M.L. Collyer, and M.E. Douglas. 2016. Deconstructing a species-complex: geometric morphometric and molecular analyses define species in the Western Rattlesnake (*Crotalus viridis*). *PloS One*. 11(1):e0146166.

Collyer, M.L., D.J. Sekora, and D.C. Adams. 2015. A method for analysis of phenotypic change for phenotypes described by high-dimensional data. *Heredity*. 115: 357-365.

Denton, J.S.S., and D.C. Adams. 2015. A new phylogenetic test for comparing multiple high-dimensional evolutionary rates suggests interplay of evolutionary rates and modularity in lanternfishes (Myctophiformes; Myctophidae). *Evolution*. 69:2425-2440.

Adams, D.C., and M.L. Collyer. 2015. Permutation tests for phylogenetic comparative analyses of high-dimensional shape data: what you shuffle matters. *Evolution*. 69:823-829. 

Adams, D.C. 2014. A method for assessing phylogenetic least squares models for shape and other high-dimensional multivariate data. *Evolution*. 68:2675-2688. 

Adams, D.C. 2014. A generalized K statistic for estimating phylogenetic signal from shape and other high-dimensional multivariate data. *Systematic Biology*. 63:685-697. 

Adams, D.C. and R. Felice. 2014. Assessing phylogenetic morphological integration and trait covariation in morphometric data using evolutionary covariance matrices. *PLoS One*. 9(4):e94335. 

Adams, D.C. 2014. Quantifying and comparing phylogenetic evolutionary rates for shape and other high-dimensional phenotypic data. *Systematic Biology*. 63:166-177. 

Collyer, M. L., and D.C. Adams. 2013. Phenotypic trajectory analysis: Comparison of shape change patterns in evolution and ecology. *Hystrix*. 24:75-83.

Adams, D.C., and M.L. Collyer. 2009. A general framework for the analysis of phenotypic trajectories in evolutionary studies. *Evolution*. 63:1143-1154. 

Adams, D. C., and M.L. Collyer. 2007. Analysis of character divergence along environmental gradients and other covariates. *Evolution*. 61:510-515. 

Collyer, M. L., and D. C. Adams. 2007. Analysis of two-state multivariate phenotypic change in ecological studies. *Ecology*. 88:683-692. 

Adams, D. C. 1999. Methods for shape analysis of landmark data from articulated structures. *Evolutionary Ecology Research.* 1:959-970.

**Further Statistical Theory Reading**

Commenges, D. 2003. Transformations which preserve exchangeability and application to permutation tests. *Journal of Nonparametric Statistics*. 15:171-185.

Anderson, M. J. (2001a). A new method for non-parametric multivariate analysis of variance. *Austral Ecology*. 26, 32–46.

Anderson, M. J. (2001b). Permutation tests for univariate or multivariate analysis of variance and regression. *Canadian Journal of Fisheries and Aquatic Sciences, 58*. 626–639. 

Gower J.C. 1966. Some distance properties of latent root and vector methods used in multivariate analysis. *Biometrika*. 53:325–338.
